name: Demo-script

on: 
  push:
    branches-ignore:
    - '!master'

jobs:

  super-lint:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:
      - name: Start Selenoid Server
        uses: Xotabu4/selenoid-github-action@v1
      - uses: actions/checkout@v1
      - name: Install Depenecies
        env:
          SELENIDE_HUB_HOST: 'localhost'
        run: mvn clean test
      - name: Create Report
        run: allure serve
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
         PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PUBLISH_BRANCH: gh-pages
         PUBLISH_DIR: allure-history
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
