name: Demo-script

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run tests
        run: mvn clean test
