name: Super-Linter

on: push


jobs:

  super-lint:
 
    name: Lint code base

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        run: mvn clean test
      

        
        
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
    with:
       allure_results: build/allure-results
       gh_pages: gh-pages
       allure_report: target/allure-report
       allure_history: target/allure-history
      
 
      - name: Run docker  
        run: docker run -v ${PWD}:/github/workspace allure-gen allure-results allure-report
      
      
        
        
        
        
        

