name: Demo-script

on: 
  push:
    branches-ignore:
    - '!master'

jobs:

  super-lint:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:
      - name: Start Selenoid Server
        run: mvn clean test
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
