name: Demo-script

on: 
  push:
    branches-ignore:
    - '!master'

jobs:

  super-lint:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest]

    steps:
      - name: Start Selenoid Server
        uses: Xotabu4/selenoid-github-action@v1
      - uses: actions/checkout@v1
      - name: Install Depenecies
        env:
          SELENIDE_HUB_HOST: 'localhost'
        run: mvn clean test
        
        
        
        
        
        
        
        
        
